// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Donald Gifford

package bootstrap

import (
	"slices"
	"strings"

	version "github.com/hashicorp/go-version"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

const headerComment = `# Generated by ` + "`sluice bootstrap`" + `. Review before committing:
#   1. Set mirror.bucket to your mirror bucket (validate passes with the
#      placeholder; plan/apply will not).
#   2. Confirm region and the default platform matrix.
`

// render emits the manifest HCL: header comment, a placeholder mirror
// block that passes validation as-is, then provider blocks sorted
// lexically by full address (hostname-major, then namespace, then
// type — the spec's "grouped by namespace" within one stream) with
// versions sorted version-aware.
func render(providers map[string]map[string]struct{}) []byte {
	f := hclwrite.NewEmptyFile()
	body := f.Body()

	body.AppendUnstructuredTokens(hclwrite.Tokens{{
		Type:  hclsyntax.TokenComment,
		Bytes: []byte(headerComment),
	}})

	mirror := body.AppendNewBlock("mirror", nil).Body()
	mirror.SetAttributeValue("bucket", cty.StringVal("CHANGE-ME-mirror-bucket"))
	mirror.SetAttributeValue("region", cty.StringVal("us-east-1"))
	mirror.SetAttributeValue("platforms", cty.ListVal([]cty.Value{
		cty.StringVal("linux_amd64"),
		cty.StringVal("darwin_arm64"),
	}))

	for _, source := range sortedSources(providers) {
		body.AppendNewline()
		block := body.AppendNewBlock("provider", []string{source}).Body()
		vals := make([]cty.Value, 0, len(providers[source]))
		for _, v := range sortedVersions(providers[source]) {
			vals = append(vals, cty.StringVal(v))
		}
		block.SetAttributeValue("versions", cty.ListVal(vals))
	}

	return f.Bytes()
}

// sortedSources returns provider addresses lexically sorted —
// hostname-major, then namespace, then type.
func sortedSources(providers map[string]map[string]struct{}) []string {
	out := make([]string, 0, len(providers))
	for s := range providers {
		out = append(out, s)
	}
	slices.Sort(out)
	return out
}

// sortedVersions returns a version set version-aware sorted. Keys are
// normalized at intake, so parsing cannot fail; a corrupt key would
// have errored in parseLock.
func sortedVersions(set map[string]struct{}) []string {
	out := make([]string, 0, len(set))
	parsed := make(map[string]*version.Version, len(set))
	for s := range set {
		out = append(out, s)
		parsed[s] = version.Must(version.NewVersion(s))
	}
	slices.SortFunc(out, func(a, b string) int {
		if c := parsed[a].Compare(parsed[b]); c != 0 {
			return c
		}
		return strings.Compare(a, b)
	})
	return out
}
