# Generated by `sluice bootstrap`. Review before committing:
#   1. Set mirror.bucket to your mirror bucket (validate passes with the
#      placeholder; plan/apply will not).
#   2. Confirm region and the default platform matrix.
mirror {
  bucket    = "CHANGE-ME-mirror-bucket"
  region    = "us-east-1"
  platforms = ["linux_amd64", "darwin_arm64"]
}

provider "registry.opentofu.org/hashicorp/null" {
  versions = ["3.2.4"]
}

provider "registry.terraform.io/cloudflare/cloudflare" {
  versions = ["5.4.0"]
}

provider "registry.terraform.io/hashicorp/aws" {
  versions = ["6.2.0", "6.3.0"]
}
